### ISSUE TITLE
Page messed up by Dreditor

### ISSUE THREAD

**Issue by salvis** [dreditor/dreditor#71]
The file table on the https://www.drupal.org/project/taxonomy_permissions/issues/2606040 page comes up completely garbled in the current Chrome/Win7 65.0.3325.146 (Official Build) (64-bit) and Dreditor 1.2.17. It looks fine in Firefox without Dreditor.

![image](https://user-images.githubusercontent.com/373828/37150400-d63acc30-22d1-11e8-9e23-a7ee358d7d76.png)

**Comment by subhojit777** [comment]
Please create the issue here https://github.com/unicorn-fail/dreditor This dreditor version is no longer maintained. I will soon close this repository. Thanks.
